from typing import Any, Protocol

from app.domain.models import DatasetMetadata, DatasetSnapshot, ModelMetadata, TrainingArtifact


class DatasetRepository(Protocol):
    def list_datasets(self) -> list[DatasetMetadata]: ...
    def get_dataset(self, dataset_id: str) -> DatasetSnapshot: ...
    def save_csv(self, filename: str, content: bytes) -> DatasetMetadata: ...


class Preprocessor(Protocol):
    def prepare(self, records: list[dict[str, Any]], target_column: str, feature_columns: list[str] | None): ...


class FeatureTransformer(Protocol):
    def build(self, feature_columns: list[str], records: list[dict[str, Any]]): ...


class ModelTrainer(Protocol):
    def train(self, dataset: DatasetSnapshot, target_column: str, algorithm: str, test_size: float, random_state: int, feature_columns: list[str] | None) -> TrainingArtifact: ...
    def load(self, artifact: bytes) -> Any: ...
    def predict(self, artifact: bytes, features: list[dict[str, Any]]) -> list[Any]: ...


class ModelEvaluator(Protocol):
    def evaluate(self, actual: list[Any], predicted: list[Any]) -> dict[str, float]: ...


class ModelRepository(Protocol):
    def save(self, model_name: str, dataset: DatasetSnapshot, target_column: str, algorithm: str, artifact: bytes, training: TrainingArtifact) -> ModelMetadata: ...
    def load(self, model_id: str, version: str) -> tuple[ModelMetadata, bytes]: ...
    def list_models(self) -> list[ModelMetadata]: ...
    def list_versions(self, model_id: str) -> list[ModelMetadata]: ...
