from typing import Protocol

from app.domain.models import DocumentPage, DocumentRecord, DownstreamHealth, KnowledgeSearchResult


class RagServiceClient(Protocol):
    def search(self, query: str, top_k: int) -> KnowledgeSearchResult: ...
    def health(self) -> DownstreamHealth: ...


class DocumentServiceClient(Protocol):
    def get_document(self, document_id: str) -> DocumentRecord: ...
    def list_documents(self, limit: int, offset: int) -> DocumentPage: ...
    def health(self) -> DownstreamHealth: ...
